---
- name: creating multiple user on OS Level 
  hosts: localhost 
  become: true
  tasks:
    - name: creating multiple user on OS Level 
      user:
        name: "{{ item }}"
        state: present 
      loop:
        - test1
        - test2
        - test3
        - test4
        - test5
        - hal-logia-d01
        - hal-logia-d02
        - hal-logia-d03
        - mware-q01
        - mware-q02
        - mware-q03
        - nvmum-{0..3}
        - jio-dev02