---
- hosts: localhost
  become: true
  tasks:
    - name: create some test users
      ansible.builtin.user:
        name: "{{ item }}"
        state: absent 
      with_sequence: start=0 end=100 format=testuser%02x